-- The following SQL needs `allow_system_table_mods = on` to run.
-- Unfortunately, it's not very well-supported.
-- I mean, it segfaults postgres.
-- Not cool.

-- Additional pg_attribute columns
-- ALTER TABLE pg_attribute ADD COLUMN attisdistkey boolean;
-- ALTER TABLE pg_attribute ADD COLUMN attencrypttype smallint;
-- ALTER TABLE pg_attribute ADD COLUMN attencodingtype smallint;
-- ALTER TABLE pg_attribute ADD COLUMN attispreloaded boolean;
-- ALTER TABLE pg_attribute ADD COLUMN attsortkeyword integer;
